CREATE DATABASE IF NOT EXISTS mathdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'app'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON mathdb.* TO 'app'@'localhost';
FLUSH PRIVILEGES;
